// <copyright file="EmailWorkTest.Constructor.g.cs">© 2014 Zachary Karpinski. All rights reserved.</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace TDriver
{
    public partial class EmailWorkTest
    {
    }
}
